import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity persisting the $Name$ domain model to the $tableName$ table.
 *
 * Keep the entity aligned with the domain model and map between the two
 * with the mappers generated by the compRepositoryImpl template.
 *
 * ── Migration checklist (required whenever fields change) ─────────────
 *   1. Bump the @Database version (e.g. 1 → 2); keep exportSchema = true
 *      so Room writes schema JSON under app/schemas/.
 *   2. Add a Migration in the database module:
 *        val MIGRATION_1_2 = object : Migration(1, 2) {
 *            override fun migrate(db: SupportSQLiteDatabase) {
 *                db.execSQL("ALTER TABLE $tableName$ ADD COLUMN new_field TEXT")
 *            }
 *        }
 *   3. Register it: Room.databaseBuilder(...).addMigrations(MIGRATION_1_2).
 *   4. Never rename/delete an existing column in place: Room verifies the
 *      schema on launch and throws IllegalStateException on any mismatch.
 */
@Entity(tableName = "$tableName$")
data class $Entity$(
    // Auto-generated surrogate primary key.
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0,

    @ColumnInfo(name = "$fieldOne$")
    val $FieldOne$: String = "",

    @ColumnInfo(name = "$fieldTwo$")
    val $FieldTwo$: String = "",
)
